export const proteins = [
  { name: 'Escolha sua proteina', protein: 0 },
  { name: 'ovos', protein: 13.3 },
  { name: 'Frango', protein: 32, fat: 5 },
  { name: 'Sobrecoxa de Frango sem pele', protein: 29, fat: 5 },
  { name: 'Coxa de Frango sem pele', protein: 23, fat: 5 },
  { name: 'Patinho (SEM GORDURAS)', protein: 36, fat: 12 },
  { name: 'Estrogonofe de carne(pouca gordura) ', protein: 28, fat: 12 },
  { name: 'Estrogonofe de frango(pouca gordura) ', protein: 25, fat: 12 },
  { name: 'Salmão ', protein: 26, fat: 14 },
  { name: 'Sardinha ', protein: 30, fat: 4 },
  { name: 'Corvina ', protein: 25, fat: 4 },
  { name: 'Acem (SEM GORDURAS)', protein: 27, fat: 15 },
  { name: 'Camarão', protein: 23, fat: 2 },
  { name: 'Contra Filé (SEM GORDURAS)', protein: 37, fat: 14 },
  { name: 'Atum ', protein: 29, fat: 1 },
  { name: 'Couxão Mole (SEM GORDURAS)', protein: 32.5, fat: 15 },
  { name: 'Figado', protein: 30, fat: 15 },
  { name: 'Filé Mignon (SEM GORDURAS)', protein: 33, fat: 17 },
  { name: 'Lagarto Cozido (SEM GORDURAS)', protein: 33, fat: 17 },
  {
    name: 'Carne de porco (SEM GORDURAS)',
    protein: 27,
    fat: 3,
  },

  { name: 'Carne de pato (SEM GORDURAS)', protein: 28, fat: 5 },
  {
    name: 'Carne de coelho(SEM GORDURAS)',
    protein: 25,
    fat: 6,
  },
];

export const carbo = [
  { name: 'Escolha seu Carboidrato', carbo: 0 },
  { name: 'Biscoito, salgado, cream cracker ', carbo: 70 },
  { name: 'Aveia', carbo: 66.6 },
  { name: 'Tapioca', carbo: 70 },
  { name: 'Cuscuz de milho ', carbo: 27 },
  { name: 'Mandioca cozida', carbo: 35 },
  { name: 'Torrada, pão francês', carbo: 75 },
  { name: 'Curau, milho verde', carbo: 16 },
  { name: 'Arroz branco cozido', carbo: 28, glycemic: 73 },
  { name: 'Arroz integral cozido', carbo: 25.8, glycemic: 68 },
  { name: 'Macarão', carbo: 75, glycemic: 80 },
  { name: 'Macarão integral', carbo: 63, glycemic: 80 },
  { name: 'Pão frances', carbo: 58, glycemic: 80 },
  { name: 'Pão integral', carbo: 47, glycemic: 50 },
  { name: 'Pão de queijo', carbo: 53, glycemic: 50 },
  { name: 'Feijão com Arroz branco ', carbo: 29, glycemic: 50 },
  { name: 'Feijão com Arroz integal ', carbo: 27, glycemic: 50 },
  { name: 'Canjica, com leite integral ', carbo: 25 },
  { name: 'Bolos ', carbo: 84.7 },
  { name: ' Cereais, milho, flocos, com sal ', carbo: 82 },
];
export const vegetables = [
  { name: 'Nenhum legume.', carbo: 0 },
  { name: 'Mandioca cozida', carbo: 35 },
  { name: 'Batata doce cozido', carbo: 20, glycemic: 61 },
  { name: 'Batata inglesa cozido', carbo: 17, glycemic: 61 },
  { name: 'Cenoura com beterraba', carbo: 15, glycemic: 51 },

  { name: 'Inhame', carbo: 20, glycemic: 51 },
  { name: 'Abóbora cozida', carbo: 11, glycemic: 64 },
];

export const salads = [
  { name: 'Escolha de Salada', weight: 0 },
  { name: 'Cenoura', weight: 2 },
  { name: 'Beterraba', weight: 2 },
  { name: 'Abobrinha', weight: 2 },
  { name: 'Beringela', weight: 2 },
  { name: 'Chuchu', weight: 2 },
  { name: 'Brocolis', weight: 2 },
  { name: 'Salada de repolho com iogurte', weight: 2 },
  { name: 'Salada Caesar', weight: 3 },
  { name: 'Salada legumes cozido', weight: 3 },
  { name: 'Salada legumes com pouca maionese', weight: 1 },
  { name: 'Salada de tomate', weight: 2 },
  { name: 'Salada de pepino', weight: 5 },
  { name: 'Salada de repolho', weight: 5 },
  { name: 'Salada de agrião', weight: 5 },
  { name: 'Salada de couve', weight: 5 },
  { name: 'Salada de rucula', weight: 5 },
  { name: 'Salada de esprinafre', weight: 5 },
  { name: 'Salada de vagem e cenoura', weight: 2 },
  { name: 'Salada de abobrinha ', weight: 2 },
  { name: 'Salada de brócolis ', weight: 2 },
  { name: 'Salada de berinjela ', weight: 2 },
  { name: 'Salada de alface ', weight: 5 },
  { name: 'Salada de agrião ', weight: 5 },
  { name: 'Salada de tomate com cebola ', weight: 5 },
];
